Treat symlinked GOPATH correctly
Right now $GOPATH can not be a symlink because govendor throws the
following error:

    Error: Package "/Users/me/Developer/project" not a go package or not in GOPATH.

This breaks typical Mac OS X setup when go is installed with homebrew
because $GOPATH is a symlink:

    % echo $GOPATH
    /usr/local/opt/go
    % ls -l /usr/local/opt/go
    /usr/local/opt/go -> ../Cellar/go/1.8

Fixes #260