Fix removal of tabulation character
There are multiple ways to fix the issue with cutset:
* Interpreted string instead of raw string
* Valid tab character in the raw string

But in my opinion, a mix of TrimSpace and Trim with raw cutset
looks more robust. One problem at a time...

Before the fix:

--- FAIL: TestParse (0.00s)
        pkgspec_test.go:55: For "tab", round tripped to "ab"

Fixes #112.